"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.find = void 0;

var _path = _interopRequireDefault(require("path"));

var _coffeescript = _interopRequireDefault(require("coffeescript"));

var _FindGraphQLTags = require("relay-compiler-language-typescript/lib/FindGraphQLTags");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// Generated by CoffeeScript 2.3.2
var find = function find(text, filePath) {
  var ref;

  if ((ref = _path.default.extname(filePath)) === '.coffee' || ref === '.cjsx') {
    text = _coffeescript.default.compile(text);
  }

  return (0, _FindGraphQLTags.find)(text, filePath);
};

exports.find = find;