"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = _default;

var _RelayLanguagePluginJavaScript = _interopRequireDefault(require("relay-compiler/lib/RelayLanguagePluginJavaScript"));

var _FindGraphQLTags = require("./FindGraphQLTags");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// Generated by CoffeeScript 2.3.2
function _default() {
  return {
    inputExtensions: ["js", "jsx", "coffee", "cjsx"],
    outputExtension: "js",
    findGraphQLTags: _FindGraphQLTags.find,
    typeGenerator: (0, _RelayLanguagePluginJavaScript.default)().typeGenerator,
    formatModule: (0, _RelayLanguagePluginJavaScript.default)().formatModule
  };
}

;